// Types for Auth
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';

// Types for Income
export const CREATE_INCOME = 'CREATE_INCOME';
export const GET_INCOMES = 'GET_INCOMES';
export const DELETE_INCOME = 'DELETE_INCOME';
export const UPDATE_INCOME = 'UPDATE_INCOME';

// Types for Expenses
export const CREATE_EXPENSE = 'CREATE_EXPENSE';
export const GET_EXPENSES = 'GET_EXPENSES';
export const DELETE_EXPENSE = 'DELETE_EXPENSE';
export const UPDATE_EXPENSE = 'UPDATE_EXPENSE';
